config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :items do
    resources :reviews, only:[:create, :destroy]
    resources :favorites, only:[:create, :destroy]

    collection do
      get :index_used
    end
  end

  resources :users do
    collection do
      get :favorites
      get :top
      get :purchase_history
    end
    member do
      patch :delivery_update
      post :favorite
      get :delete
      post :delete
    end
  end

  get '/admin/users/:id/edit' => 'users#admin_edit', as: 'admin_edit'

  resources :contacts, only:[:create, :show, :index]
  get '/contacts_top' => 'contacts#top', as: 'contact_top'

  resources :carts, only:[:index, :show]
  get '/function/:id' => 'carts#function', as: 'cart_function'
  get '/complete' => 'carts#complete', as: 'cart_complete'
  post '/carts/:id/add_item'  => 'carts#add_item', as: 'cart_add_item'
  post '/carts/:id' => 'carts#address_change', as: 'carts_address_change'
  post '/buy' => 'carts#buy', as: 'purchase_histories'
  patch '/carts/:id/update' => 'carts#update', as: 'cart_update'
  delete '/carts/:id/destroy' => 'carts#delete', as: 'cart_delete'

  resources :homes, only:[:index]
  get '/' => 'homes#top',as: "top"

  resources :artists, only:[:show, :create, :new, :destroy]
  get 'artists/:id/new_item' => 'artists#new_item', as: 'artist_new_item'
  get 'artists/:id/used_item' => 'artists#used_item', as: 'artist_used_item'

  resources :genre, only:[:index, :create]
  resources :lable, only:[:index, :create]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/artist.rb
class Artist < ApplicationRecord

  has_many :items

  attachment :artist_image

  validates :artist_name, presence: true

end

app/models/cart.rb
class Cart < ApplicationRecord

	belongs_to :user
	belongs_to :item
	has_one :purchase_history

    acts_as_paranoid
end

app/models/contact.rb
class Contact < ApplicationRecord

	belongs_to :user

	validates :contact_title, presence: true
	validates :contact_text, presence: true

end

app/models/delivery.rb
class Delivery < ApplicationRecord

	has_many :purchase_histories

end

app/models/disc.rb
class Disc < ApplicationRecord

  belongs_to :item, required: true
  has_many :songs, dependent: :destroy

  accepts_nested_attributes_for :songs, reject_if: :all_blank, allow_destroy: true

  validates :disc_name, presence: true


end

app/models/favorite.rb
class Favorite < ApplicationRecord

	belongs_to :user
    belongs_to :item

end

app/models/genre.rb
class Genre < ApplicationRecord

  has_many :items

  validates :genre_name, presence: true

end

app/models/item.rb
class Item < ApplicationRecord

  belongs_to :artist, required: true
  belongs_to :lable, required: true
  belongs_to :genre, required: true

  has_many :discs, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :carts

  attachment :item_image

  accepts_nested_attributes_for :discs, reject_if: :all_blank, allow_destroy: true

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  validates :item_name, presence: true
  validates :item_states, presence: true
  validates :item_type, presence: true
  validates :price, presence: true
  validates :stock, presence: true

end

app/models/lable.rb
class Lable < ApplicationRecord

  has_many :items

  validates :lable_name, presence: true

end

app/models/review.rb
class Review < ApplicationRecord

	belongs_to :user
	belongs_to :item

	validates :review_title, length: { in:1..20}
	validates :review_text, length: { in:1..200}

end

app/models/song.rb
class Song < ApplicationRecord

	belongs_to :disc, required: true

	validates :song_title, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :contacts
  has_many :favorites, dependent: :destroy
  has_many :purchase_histories
  has_many :reviews, dependent: :destroy
  has_many :carts, dependent: :destroy

  validates :email, presence: true
  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :zip_code, presence: true
  validates :address, presence: true
  validates :phone_number, presence: true

  paginates_per 12

  acts_as_paranoid
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def top
  end

  def edit
    @user = User.find(params[:id])
  end

  def admin_edit
    @user = User.find(params[:id])
  end

  def admin_update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to top_path
  end

  def purchase_history
    @user = current_user
    @histories = @user.purchase_histories
    @carts = current_user.carts
    @bought = @carts.with_deleted
  end

  def delivery_update
    @user = User.find(params[:id])
    @purchase_histories = @user.purchase_histories
    @purchase_history = @purchase_histories.find_by(id: params[:purchase_history][:id])
    @purchase_history.delivery_id = @purchase_histories.find_by(params[:purchase_history][:delivery_id])
    @purchase_history.update(purchase_history_params)
    redirect_to top_path
  end


  def favorites
    @favorites = current_user.favorites.page(params[:page]).per(PER).reverse_order
    @items = Item.page(params[:page]).per(12)
  end

  def delete
    user = current_user
    user.destroy
    flash[:notice] = "退会しました"
    redirect_to top_path
  end

  PER = 3
  def index
    @users = User.all.page(params[:page]).per(PER).reverse_order
    @q = User.ransack(params[:q])
    @users = @q.result(distinct: true).page(params[:page]).per(PER).reverse_order
    @items = Item.page(params[:page]).per(12)
  end

  def show
    @user = User.find(params[:id])
    @histories = @user.purchase_histories
    @carts = current_user.carts
    @bought = @carts.with_deleted
    @delivery = Delivery.all
  end

  def update
    @user = User.find(params[:id])
    @user.update!(user_params)
    redirect_to top_path
  end

  def destroy
    user = User.find(params[:id])
    user.destroy
    redirect_to users_path
  end

  private
  def user_params
    params.require(:user).permit(
      :email, :last_name, :first_name,
      :last_name_kana, :first_name_kana,
      :zip_code, :address, :phone_number)
  end

  def purchase_history_params
    params.require(:purchase_history).permit(:delivery_id)
  end

end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/genre_helper.rb
module GenreHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/lable_helper.rb
module LableHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/admin_edit.erb
<div class="admin-user-edit">
 <h1 class="user-registration-title"><span class="label label-default">
 ユーザー編集</span></h1>
  <%=  form_for(@user) do |f| %>

		<%# パスワードを入力したい
		f.hidden_field :password %>

	<div class="field form-group">
		<%= f.label :last_name, "名前（姓）" %>
		<%=  f.text_field :last_name, :class => "form-control" %>
		<%= f.label :first_name, "名前（名）" %>
		<%=  f.text_field :first_name, :class => "form-control" %>
	</div>

	<div class ='field form-group'>
		<%= f.label :last_name_kana, "名前カナ（姓）" %>
		<%=  f.text_field :last_name_kana, :class => "form-control" %>
		<%= f.label :first_name_kana, "名前カナ（姓）" %>
		<%=  f.text_field :first_name_kana, :class => "form-control" %>
	</div>

	<div class ='field form-groupe'>
		<%= f.label :zip_code, "郵便番号" %>
		<%=  f.text_field :zip_code, :class => "form-control" %>
	</div>

	<div class ='field form-group'>
		<%= f.label :address, "住所" %>
		<%=  f.text_field :address, :class => "form-control" %>
	</div>

	<div class = 'field form-group'>
		<%= f.label :phone_number, "電話番号" %>
		<%=  f.text_field :phone_number, :class => "form-control" %>
	</div>

	<div class ='field form-group'>
		<%= f.label :email, "メール" %>
		<%=  f.text_field :email, :class => "form-control" %>
	</div>

    <div class="actions form-group">
		<%= f.submit '更新', :class => "btn btn-primary" %>
    </div>
 <% end %>
</div>

app/views/users/delete.html.erb
<h1>退会手続き</h1>
<p>登録したメールアドレスを入力して下さい。</p>

<%= form_for(@user) do |f| %>
  <div class="field">
    <%= f.label :メールアドレス %><br />
    <%= f.email_field :email, autofocus: true, autocomplete: "email" %>
  </div>

  <div class="field">
    <%= f.label :パスワード %><br />
    <%= f.password_field :password, autocomplete: "current-password" %>
  </div>

　<div class="actions">
    <%= f.submit "退会" %>
  </div>
<% end %>

app/views/users/edit.html.erb
<div class="user-user-edit">
	<h1 class="user-registration-title"><span class="label label-default">ユーザー編集</span></h1>

	<%=  form_for(@user) do |f| %>
	<div class="field form-group">
		<%= f.label :last_name, "名前（姓）" %>
		<%=  f.text_field :last_name, :class => "form-control" %>
		<%= f.label :first_name, "名前（名）" %>
		<%=  f.text_field :first_name, :class => "form-control" %>
	</div>

	<div class ='field form-group'>
		<%= f.label :last_name_kana, "名前カナ（姓）" %>
		<%=  f.text_field :last_name_kana %>
		<%= f.label :first_name_kana, "名前カナ（姓）" %>
		<%=  f.text_field :first_name_kana %>
	</div>

	<div class ='field form-group'>
		<%= f.label :zip_code, "郵便番号" %>
		<%=  f.text_field :zip_code %>
	</div>

	<div class ='field form-group'>
		<%= f.label :address, "住所" %>
		<%=  f.text_field :address %>
	</div>

	<div class = 'field form-group'>
		<%= f.label :phone_number, "電話番号" %>
		<%=  f.text_field :phone_number %>
	</div>

	<div class ='field form-group'>
		<%= f.label :email, "メール" %>
		<%=  f.text_field :email %>
	</div>

		<%= f.submit '更新' %>
	<% end %>
</div>

app/views/users/favorites.html.erb
<h1><span class="label label-default">お気に入り一覧</span></h1>
<div class = "item_favorite container" >
	<div class="row" >
		<div class="col-lg-10 col-lg-offset-1">
		    <% @favorites.each do |favorite| %>
			    <div class="artist-list">
			    	<div class="item-image">
				        <%= attachment_image_tag favorite.item, :item_image, size: '100x100' %>
				    </div>
				    <div class="item-name">
				      <h5><span class="label label-default">状態</span>&nbsp;&nbsp;<%= favorite.item.item_states %></h5>
				    </div>
				    <div class="artist-name">
				     <%= link_to item_path(favorite.item.id) do %>
				      <h5><span class="label label-default">商品名</span>&nbsp;&nbsp;<%= favorite.item.item_name %></h5>
				     <% end %>
				    </div>
				    <div class="item-price">
				     <%= link_to item_path(favorite.item.artist.id) do %>
				      <h5><span class="label label-default">アーティスト</span>&nbsp;&nbsp;<%= favorite.item.artist.artist_name %></h5>
				     <% end %>
				    </div>
				    <div class="item-stock">
				      <h5><span class="label label-default">価格</span>&nbsp;&nbsp;<%= favorite.item.price %>円</h5>
				    </div>
				    <div class="item-stock">
				      <% if favorite.item.stock == 0 %>
                        <h5 class="label label-danger"><%= 'Sold Out' %></h5><%= 'Sold Out' %>
                      <% end %>
                   </div>
			    </div>
		    <% end %>
	    </div>
    </div>
   <div class="favorite-paginate">
     <%= paginate @favorites %>
   </div>
</div>

app/views/users/index.html.erb
<h1><span class="label label-default">ユーザー一覧</span></h1>

<div class="user-index-admin">
	<div class="form-horizontal" role="form">
	    <%= search_form_for @q do |f| %>
	      <div class="search-user" >
	 		<div class="form-group">
		      <%= f.label :last_name_cont, "ユーザー検索" %>
		    </div>
		    <div class="col-xs-10">
			  <%= f.search_field :last_name_or_first_name_cont, :class => "form-control", placeholder: "ユーザー名（姓）" %>
			</div>
		  </div>
			  <%= f.submit "検索", :class => "btn btn-primary" %>
		<% end %>
	</div>
</div>


 <div class="container" >
     <div class="col-lg-6 user-list">
	    <table class="table">
	    	<thead>
	      		<th>name</th>
	      		<th></th>
	            </thead>
	            <% @users.each do |user| %>
	            <thead>
			    <th><%= user.last_name %><%= user.first_name %></th>
			    <th><%= button_to "詳細", user_path(user.id), method: :get, class: 'btn btn-default' %></th>
	         <% end %>
		    </thead>
		</table>
	 </div>
 </div>

 <div class="user-admin-index-paginate">
   <%= paginate @users %>
 </div>

app/views/users/purchase_history.html.erb
<div class="purchase-history clearfix">
  <h1>購入履歴一覧</h1>
  <% sum = 0 %>

    <% @histories.zip(@bought).each do |history,cart| %>
      <div class="history-item ">
        <div class="history-image">
            <%= attachment_image_tag cart.item, :item_image, size: "200x200", fallback: "no_image.jpg" %>
        </div>
        <div class="">
            <h4><%= cart.item.item_name  %></h4>
        </div>
        <div class="">
            <h4><%= link_to cart.item.artist.artist_name, artist_path(cart.item.artist.id) %></h4>
        </div>
        <div class="">
            <h4><%= history.bought_price %>円</h4>
        </div>
        <div class="">
    	    <h4><%= cart.cart_item %>枚</h4>
        </div>
        <div class="">
            <h4><%= history.created_at.strftime('%Y/%m/%d') %></h4>
        </div>
        <div class="">
            <h4><%= cart.delivery_zip_code %></h4>
        </div>
        <div class="">
            <h4><%= cart.delivery_address %></h4>
        </div>
        <div class="">
            <%  if history.delivery_id != nil %>
            <%= history.delivery.delivery_state %>
            <% end %>
        </div>
      </div>
      <% a = cart.cart_item*history.bought_price %>
    <% sum += a %>
    <% end %>
</div>
<div class="">
    <h2 class="total-price">合計金額 <%= sum %>円</h2>
  </div>

app/views/users/show.html.erb
<h1>ユーザー詳細</h1>
<div class = 'user_information'>
	<ul>
		<li class="name">
			<h2> 姓　<%= @user.last_name %>
			　名　<%= @user.first_name %></h2>
		</li>
		<li class="name-kana">
			<h2> セイ　<%= @user.last_name_kana %>
			　メイ　<%= @user.first_name_kana %></h2>
		</li>
		<li class="zip">
			<h2> 住所　<%= @user.zip_code %></h2>
		</li>
		<li class="address">
			<h2> メールアドレス　<%= @user.address %></h2>
		</li>
		<li class="phone-number">
			<h2> 電話番号　<%= @user.phone_number %></h2>
		</li>
		<li class="email">
			<h2> 郵便番号　<%= @user.email %></h2>
        </li>
    </ul>

	<%= link_to "編集", admin_edit_path(@user.id), class: "btn btn-success admin_edit_#{@user.id}" %>
	<%= link_to "削除", user_path(@user.id), class: "btn btn-danger user_#{@user.id}", method: :delete, "data-confirm" => "本当に削除しますか？" %>

</div>

<h1>購入履歴一覧</h1>

		<div class = "user_purchase_history clearfix">
		  <% if @histories.exists? %>
			<% @histories.zip(@bought).each do |history,cart| %>
			    <div class="purchase_history">
				    <%= form_for history, :url => {:action => 'delivery_update'} do |f| %>
				    <%= f.hidden_field :id,:value => history.id %>
				    <%= f.select :delivery_id, @delivery.map{|t| [t.delivery_state, t.id]}, :prompt => "選択してください" %>
				    <%= f.submit '登録' %>
			<% end %>
				    <div class="show-item-image">
				        <%= attachment_image_tag cart.item, :item_image, size: "200x200", fallback: "no_image.jpg" %>
				    </div>
		            <div class="show-item-information">
				        <h4><%= cart.item.item_name  %></h4>
				    </div>
				    <div class="show-item-information">
				        <h4><%= link_to cart.item.artist.artist_name, artist_path(cart.item.artist.id) %></h4>
				    </div>
				    <div class="show-item-information">
				        <h4><%= history.bought_price %>円 </h4>
				    </div>
				    <div class="show-item-information">
					    <h4><%= cart.cart_item %>枚 </h4>
					</div>
					<div class="show-item-information">
						<h4><%= cart.delivery_address %></h4>
					</div>
					<div class="show-item-information">
				        <h4><%= history.created_at.strftime('%Y/%m/%d') %></h4>
				    </div>
			    </div>
			    <% end %>
		  <% else %>
			     <h1>購入履歴はありません</h1>
		  <% end %>
		</div>

app/views/users/top.html.erb
<div class="top-text">

	<% if current_user.admin == true %>
    <div class="container">
        <div class="row">
            <div class="col-lg-1">
            </div>
            <div class="col-lg-5">
        	    <div class="box1">
                    <p class="purchase_history_users"><%= link_to "新品商品一覧", items_path %></p>
                </div>
                <div class="box3">
                    <p class="user-index"><%= link_to "ユーザー一覧", users_path %></p>
                </div>
            </div>
            <div class="col-lg-5">
                <div class="box2">
                    <p class="favorites_users"><%= link_to "中古商品一覧", index_used_items_path %></p>
                </div>
                <div class="box4">
                    <p class="delete_user"><%= link_to "商品追加", new_item_path %></p>
                </div>
            </div>
            <div class="col-lg-4">
            </div>
            <div class="col-lg-5">
                <div class="box5">
                    <p class="contact-index"><%= link_to "問い合わせ一覧", contacts_path %></p>
                </div>
            </div>
            <div class="col-lg-4">
            </div>
        </div>
    </div>

    <% else %>

    <div class="container">
        <div class="row">
            <div class="col-lg-1">
            </div>
            <div class="col-lg-5">
                <div class="box1">
    	            <p class="purchase_history_users"><%= link_to "購入履歴一覧", purchase_history_users_path %></p>
                </div>
                <div class="box3">
                    <p class="user-edit"><%= link_to "ユーザー編集", edit_user_path(current_user.id) %></p>
                </div>
    	    </div>
            <div class="col-lg-5">
    	        <div class="box2">
    		        <p class="favorites_users"><%= link_to "お気に入り一覧", favorites_users_path %></p>
    	        </div>
                <div class="box4">
    		        <p class="delete_user"><%= link_to "退会", delete_user_path(current_user.id) %></p>
	            </div>
            </div>
        <% end %>
    </div>
</div>