config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :items do
    resources :reviews, only:[:create, :destroy]
    resources :favorites, only:[:create, :destroy]

    collection do
      get :index_used
    end
  end

  resources :users do
    collection do
      get :favorites
      get :top
      get :purchase_history
    end
    member do
      patch :delivery_update
      post :favorite
      get :delete
      post :delete
    end
  end

  get '/admin/users/:id/edit' => 'users#admin_edit', as: 'admin_edit'

  resources :contacts, only:[:create, :show, :index]
  get '/contacts_top' => 'contacts#top', as: 'contact_top'

  resources :carts, only:[:index, :show]
  get '/function/:id' => 'carts#function', as: 'cart_function'
  get '/complete' => 'carts#complete', as: 'cart_complete'
  post '/carts/:id/add_item'  => 'carts#add_item', as: 'cart_add_item'
  post '/carts/:id' => 'carts#address_change', as: 'carts_address_change'
  post '/buy' => 'carts#buy', as: 'purchase_histories'
  patch '/carts/:id/update' => 'carts#update', as: 'cart_update'
  delete '/carts/:id/destroy' => 'carts#delete', as: 'cart_delete'

  resources :homes, only:[:index]
  get '/' => 'homes#top',as: "top"

  resources :artists, only:[:show, :create, :new, :destroy]
  get 'artists/:id/new_item' => 'artists#new_item', as: 'artist_new_item'
  get 'artists/:id/used_item' => 'artists#used_item', as: 'artist_used_item'

  resources :genre, only:[:index, :create]
  resources :lable, only:[:index, :create]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/artist.rb
class Artist < ApplicationRecord

  has_many :items

  attachment :artist_image

  validates :artist_name, presence: true

end

app/models/cart.rb
class Cart < ApplicationRecord

	belongs_to :user
	belongs_to :item
	has_one :purchase_history

    acts_as_paranoid
end

app/models/contact.rb
class Contact < ApplicationRecord

	belongs_to :user

	validates :contact_title, presence: true
	validates :contact_text, presence: true

end

app/models/delivery.rb
class Delivery < ApplicationRecord

	has_many :purchase_histories

end

app/models/disc.rb
class Disc < ApplicationRecord

  belongs_to :item, required: true
  has_many :songs, dependent: :destroy

  accepts_nested_attributes_for :songs, reject_if: :all_blank, allow_destroy: true

  validates :disc_name, presence: true


end

app/models/favorite.rb
class Favorite < ApplicationRecord

	belongs_to :user
    belongs_to :item

end

app/models/genre.rb
class Genre < ApplicationRecord

  has_many :items

  validates :genre_name, presence: true

end

app/models/item.rb
class Item < ApplicationRecord

  belongs_to :artist, required: true
  belongs_to :lable, required: true
  belongs_to :genre, required: true

  has_many :discs, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :carts

  attachment :item_image

  accepts_nested_attributes_for :discs, reject_if: :all_blank, allow_destroy: true

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  validates :item_name, presence: true
  validates :item_states, presence: true
  validates :item_type, presence: true
  validates :price, presence: true
  validates :stock, presence: true

end

app/models/lable.rb
class Lable < ApplicationRecord

  has_many :items

  validates :lable_name, presence: true

end

app/models/review.rb
class Review < ApplicationRecord

	belongs_to :user
	belongs_to :item

	validates :review_title, length: { in:1..20}
	validates :review_text, length: { in:1..200}

end

app/models/song.rb
class Song < ApplicationRecord

	belongs_to :disc, required: true

	validates :song_title, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :contacts
  has_many :favorites, dependent: :destroy
  has_many :purchase_histories
  has_many :reviews, dependent: :destroy
  has_many :carts, dependent: :destroy

  validates :email, presence: true
  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :zip_code, presence: true
  validates :address, presence: true
  validates :phone_number, presence: true

  paginates_per 12

  acts_as_paranoid
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

  before_action :authenticate_user!
  before_action :cart_confirmation, only:[:update, :delete, :address_change]
  #カート内一覧画面
  def index
    @carts = current_user.carts.where(deleted_at: nil)
  end

  #購入手続き画面
  def function
    @user_delivery = Cart.last
  end

  #購入確認画面
  def show
    @user = current_user
    @carts = current_user.carts.where(deleted_at: nil)
    @buy_item = PurchaseHistory.new
  end

  #購入完了画面
  def complete
  end

  #カートに商品を入れるアクション
  def add_item
    #商品に対してカートが作られているかどうかでアクションが変わる
    #ある場合⇨cart_itemの個数が変更される
    #ない場合⇨新たにカートを作成する
    item = Item.find(params[:id])
    current_cart = current_user.carts
     #同じ商品を買うときはすでにあるカートの中の個数を増やす
     #Cart.find_by(item_id: params[:id]) && Cart.find_by(user_id: current_user.id)
    if current_cart.exists?(:item_id => params[:id])
       cart = current_user.carts.find_by(item_id: params[:id])
       add_stock = cart.cart_item + params[:cart][:cart_item].to_i
       cart.update(cart_item: add_stock)
       #カートに入れた商品の数をアイテムから引く
       stock = item.stock - params[:cart][:cart_item].to_i
       item.stock = stock
       item.save
    else
       cart_disc = Cart.new(cart_disc_params)
       cart_disc.item_id = params[:id]
       cart_disc.user_id = current_user.id
       cart_disc.save
       #カートに入れた商品の数をアイテムから引く
       stock = item.stock - params[:cart][:cart_item].to_i
       item.stock = stock
       item.save
    end
    redirect_to items_path
  end

  #カート内の商品を編集するアクション
  def update
    cart = Cart.find(params[:id])
    cart.update(cart_update_params)
  #カートに入れた数だけ在庫数を減らす
    stock = cart.item.stock - cart.cart_item
    item = cart.item
    item.stock = stock
    item.save
    redirect_to carts_path
  end

  #カート内で商品を削除するアクション
  #⇨カートモデルのレコードを削除する
  def delete
    cart = Cart.find(params[:id])
    cart.destroy
  #カートから削除した分だけ在庫数を増やす
    stock = cart.item.stock + cart.cart_item
    item = cart.item
    item.stock = stock
    item.save
    redirect_to carts_path
  end

  #カートテーブルの配送先住所を入力するアクション
  def address_change
    carts = current_user.carts
    carts.each do |cart|
      if cart.delivery_address.nil?
       cart.delivery_address = params[:cart][:delivery_address]
      end
      if cart.delivery_zip_code.nil?
       cart.delivery_zip_code = params[:cart][:delivery_zip_code]
      end
       cart.save
    end
      redirect_to cart_path(current_user)
  end

  #カート内の商品を購入履歴に反映させるアクション
  def buy
    carts = current_user.carts.where(deleted_at: nil)
    buy_item = PurchaseHistory.new
    carts.each do |cart|
      buy_item.cart_id = cart.id
      buy_item.user_id = current_user.id
      buy_item.bought_price = cart.item.price
      buy_item.save
      cart.destroy
    end
      redirect_to cart_complete_path
  end

  #カートに商品が入っていない場合にURLからアクセスしようとした時のアクション
  def cart_confirmation
    @carts = current_user.carts.where(deleted_at: nil)
    if @carts.empty?
      flash[:notice] = "商品が選択されていません"
      redirect_to carts_path
    end
  end

  private
  def cart_disc_params
    params.require(:cart).permit(
      :cart_item, :delivery_address, :delivery_zip_code, :user_id, :item_id)
  end

  def cart_update_params
     params.require(:cart).permit(:cart_item)
  end

  def address_change_params
    params.require(:cart).permit(
      :delivery_address, :delivery_zip_code)
  end

  def _params
    params.require(:user).permit(:name, :profile_image)
end
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/genre_helper.rb
module GenreHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/lable_helper.rb
module LableHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/carts/complete.html.erb
	<div class="buy-complete">
	   <h1 class="buy-complete-message"><span class="glyphicon glyphicon-ok" aria-hidden="true"></span>購入完了</h1>
	   <h3 class="buy-complete-text">ご注文ありがとうございます。購入が確定されました。</h3>
	   <h3 class="buy-complete-body">商品の配送状況は
	  	 <%= link_to '購入履歴', purchase_history_users_path %> から確認できます。</h3>
	  <div class="my-page-back">
	   <%= link_to 'マイページへ', top_users_path, :class => "btn btn-primary btn-lg btn-block active" %>
	  </div>
	</div>
 <div class="video">
   <%= video_tag("img/PlayingGuitar.webm", :autoplay => true, :loop => true, :muted => true, :size => '1000') %>
 </div>

app/views/carts/function.html.erb
<div class="delivery-main-box">
 <h1 class="delivery-title"><span class="label label-success">配送先情報を入力</span></h1>
  <div class="col-lg-6">

    <%= form_for @user_delivery,url: carts_address_change_path, method: :post do |f| %>
     <h3><span class="label label-default">配送先郵便番号</span></h3>
      <%= f.text_field :delivery_zip_code, autocomplete: "zip_code", :class => "form-control", :size=> "80", placeholder: "郵便番号を入力してください" %>

     <h3><span class="label label-default">配送先住所</span></h3>
      <%= f.text_field :delivery_address, :class => "form-control", autocomplete: "address", :size=> "80", placeholder: "住所を入力してください" %>

      <div class="form-submit" >
     <h4><%= f.submit '次に進む', :class => "btn btn-primary btn-block active", :size=> "80" %></h4>
      </div>
   <% end %>
 </div>

</div>

app/views/carts/index.html.erb
<div class="container">

  <h1 class="cart-main-title"><span class="glyphicon glyphicon-shopping-cart" aria-hidden="true"></span>マイカート</h1>

  <% if @carts.empty? %>
    <h1 class="cart-nothing-messeage">カート内に商品がありません</h1>
    <div class="still-shopping"><%= link_to "買い物を続ける", items_path, :class => "btn btn-primary btn-lg btn-block active" %></div>
<% else %>

  <div class="col-xs-12">
   <% sum = 0 %>
      <table class="table">
      	<thead>
      		<th></th>
      		<th>商品名</th>
      		<th>アーティスト</th>
      		<th>価格</th>
      		<th>個数</th>
      		<th></th>
      		<th></th>
      	</thead>
    <% @carts.each do |cart| %>
      	<thead>
		    <th><%= attachment_image_tag cart.item, :item_image, size: "100x100", fallback: "no_image.jpg" %></th>
			<th><%= cart.item.item_name %></th>
		    <th><%= cart.item.artist.artist_name %></th>
			<th>¥<%= cart.item.price %></th>
			<th><%= cart.cart_item %></th>
			<th>
	            <%= form_for cart, url: cart_update_path(cart.id) do |f| %>
		 	      <%= f.select :cart_item, [1,2,3,4,5,6,7,8,9,10] %>
		          <%= f.submit '変更', :class => "btn btn-primary" %>
	            <% end %>
	        </th>
	        <th>
	           <%= link_to '削除', cart_delete_path(cart.id), method: :delete, :class => "btn btn-danger" %>
	        </th>
	    </thead>
	      <% a = cart.item.price*cart.cart_item %>
	      <% sum += a %>
    <% end %>
      </table>
　　　　　　<div class="total-price">
		    <% if @carts.empty? %>
		      <p></p>
		  <% else %>
		      <h4 class="alert alert-success">合計金額 <%= sum %>円</h4>
		    <% end %>
		</div>
  </div>
<% end %>

		<div class="buy_trigger">
		 <% if @carts.empty? %>
		  <div class="continue-shopping"></div>
		<% else %>
		   <%= link_to "購入手続きへ", cart_function_path(current_user), :class => "btn btn-success active" %>
		 <% end %>
		</div>

</div>

app/views/carts/show.html.erb
<div class="buy-confirmation">
	<h1 class="cart-show-title"><span class="label label-success">購入内容確認</span></h1>
   <% sum = 0 %>
      <table class="table">
      	<thead>
      		<th></th>
      		<th><span class="label label-default">商品名</span></th>
      		<th><span class="label label-default">アーティスト</span></th>
      		<th><span class="label label-default">価格</span></th>
      		<th><span class="label label-default">個数</span></th>
      	</thead>
    <% @carts.each do |cart| %>
      	<thead>
		    <th><%= attachment_image_tag cart.item, :item_image, size: "100x100", fallback: "no_image.jpg" %></th>
			<th><%= cart.item.item_name %></th>
		    <th><%= cart.item.artist.artist_name %></th>
			<th>¥<%= cart.item.price %></th>
			<th><%= cart.cart_item %></th>
	    </thead>
	      <% a = cart.item.price*cart.cart_item %>
	      <% sum += a %>
    <% end %>
      </table>
　　　　　　<div class="alert alert-success">
		    <% if @carts.empty? %>
		      <p></p>
		  <% else %>
		      <h4 class="total-price">合計金額 <%= sum %>円</h4>
		    <% end %>
		</div>

	　<div class="user-delivery-box">
	　  <div class="well"><strong>購入者情報確認</strong></div>
	      <div class="well-text" >
	         <h4 class="well-text-title">氏名</h4>
	           <h4 class="well-text-body">
		　     <%= @user.last_name %>
		       <%= @user.first_name %>
		       </h4>
		     <h4 class="well-text-title">送付先：郵便番号</h4>
		　　　  <h4 class="well-text-body"><%= @carts.last.delivery_zip_code %></h4>
		　　  <h4 class="well-text-title">送付先：住所</h4>
		　　　  <h4 class="well-text-body"><%= @carts.last.delivery_address %></h4>
		     <%= link_to '購入', purchase_histories_path, method: :post, :class => "btn btn-primary btn-lg btn-block active" %>
	     </div>
	 </div>
 </div>