config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :items do
    resources :reviews, only:[:create, :destroy]
    resources :favorites, only:[:create, :destroy]

    collection do
      get :index_used
    end
  end

  resources :users do
    collection do
      get :favorites
      get :top
      get :purchase_history
    end
    member do
      patch :delivery_update
      post :favorite
      get :delete
      post :delete
    end
  end

  get '/admin/users/:id/edit' => 'users#admin_edit', as: 'admin_edit'

  resources :contacts, only:[:create, :show, :index]
  get '/contacts_top' => 'contacts#top', as: 'contact_top'

  resources :carts, only:[:index, :show]
  get '/function/:id' => 'carts#function', as: 'cart_function'
  get '/complete' => 'carts#complete', as: 'cart_complete'
  post '/carts/:id/add_item'  => 'carts#add_item', as: 'cart_add_item'
  post '/carts/:id' => 'carts#address_change', as: 'carts_address_change'
  post '/buy' => 'carts#buy', as: 'purchase_histories'
  patch '/carts/:id/update' => 'carts#update', as: 'cart_update'
  delete '/carts/:id/destroy' => 'carts#delete', as: 'cart_delete'

  resources :homes, only:[:index]
  get '/' => 'homes#top',as: "top"

  resources :artists, only:[:show, :create, :new, :destroy]
  get 'artists/:id/new_item' => 'artists#new_item', as: 'artist_new_item'
  get 'artists/:id/used_item' => 'artists#used_item', as: 'artist_used_item'

  resources :genre, only:[:index, :create]
  resources :lable, only:[:index, :create]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/artist.rb
class Artist < ApplicationRecord

  has_many :items

  attachment :artist_image

  validates :artist_name, presence: true

end

app/models/cart.rb
class Cart < ApplicationRecord

	belongs_to :user
	belongs_to :item
	has_one :purchase_history

    acts_as_paranoid
end

app/models/contact.rb
class Contact < ApplicationRecord

	belongs_to :user

	validates :contact_title, presence: true
	validates :contact_text, presence: true

end

app/models/delivery.rb
class Delivery < ApplicationRecord

	has_many :purchase_histories

end

app/models/disc.rb
class Disc < ApplicationRecord

  belongs_to :item, required: true
  has_many :songs, dependent: :destroy

  accepts_nested_attributes_for :songs, reject_if: :all_blank, allow_destroy: true

  validates :disc_name, presence: true


end

app/models/favorite.rb
class Favorite < ApplicationRecord

	belongs_to :user
    belongs_to :item

end

app/models/genre.rb
class Genre < ApplicationRecord

  has_many :items

  validates :genre_name, presence: true

end

app/models/item.rb
class Item < ApplicationRecord

  belongs_to :artist, required: true
  belongs_to :lable, required: true
  belongs_to :genre, required: true

  has_many :discs, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :carts

  attachment :item_image

  accepts_nested_attributes_for :discs, reject_if: :all_blank, allow_destroy: true

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  validates :item_name, presence: true
  validates :item_states, presence: true
  validates :item_type, presence: true
  validates :price, presence: true
  validates :stock, presence: true

end

app/models/lable.rb
class Lable < ApplicationRecord

  has_many :items

  validates :lable_name, presence: true

end

app/models/review.rb
class Review < ApplicationRecord

	belongs_to :user
	belongs_to :item

	validates :review_title, length: { in:1..20}
	validates :review_text, length: { in:1..200}

end

app/models/song.rb
class Song < ApplicationRecord

	belongs_to :disc, required: true

	validates :song_title, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :contacts
  has_many :favorites, dependent: :destroy
  has_many :purchase_histories
  has_many :reviews, dependent: :destroy
  has_many :carts, dependent: :destroy

  validates :email, presence: true
  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :zip_code, presence: true
  validates :address, presence: true
  validates :phone_number, presence: true

  paginates_per 12

  acts_as_paranoid
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

#管理者しかできないアクションを指定
before_action :authenticate_user!, only:[:new, :edit, :create, :destroy, :status, :update]
before_action :ensure_correct_user, only:[:new, :edit, :create, :destroy, :status, :update]

  PER = 12
  def index
    @rank = Item.find(Favorite.group(:item_id).order('count(item_id) desc').limit(3).pluck(:item_id))
    @search = Item.where("item_states = '新品'").ransack(params[:q])
      if params[:q].present?
        @items = @search.result.page(params[:page]).per(PER).reverse_order
      else
        @items = Item.where("item_states = '新品'").page(params[:page]).per(PER).reverse_order
      end
  end

  def index_used
    @rank = Item.find(Favorite.group(:item_id).order('count(item_id) desc').limit(3).pluck(:item_id))
    @search = Item.where("item_states = '中古'").ransack(params[:q])
      if params[:q].present?
        @items = @search.result.page(params[:page]).per(PER).reverse_order
      else
        @items = Item.where("item_states = '中古'").page(params[:page]).per(PER).reverse_order
      end
  end

  def show
    @item = Item.find(params[:id])
    @review = Review.new
    @cart_disc = Cart.new
  end

  def new
    @item = Item.new
    @artists = Artist.all
    @genres = Genre.all
    @lables = Lable.all
  end

  def edit
    @item = Item.find(params[:id])
    @artists = Artist.all
    @genres = Genre.all
    @lables = Lable.all
  end

  def create
    item = Item.new(item_params)
    item.save
    if item.item_states == '新品'
      redirect_to items_path
    else
      redirect_to index_used_items_path
    end
  end

  def destroy
    item = Item.find(params[:id])
    item.destroy
    redirect_to items_path
  end

  def status
  end

  def update
    item = Item.find(params[:id])
    item.update(item_params)
    redirect_to items_path
  end

  def ensure_correct_user
    if current_user.admin == false
      flash[:notice] = "許可されていないアクションです"
      redirect_to top_users_path
    end
  end

  private
  def item_params
    params.require(:item).permit(:item_name, :item_image, :item_states, :item_type, :price, :stock, :deleted_at, :artist_id, :lable_id, :genre_id, discs_attributes: [:id, :disc_name, :item_id,:_destroy, songs_attributes: [:id, :song_title, :disc_id, :_destroy]])
  end
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/genre_helper.rb
module GenreHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/lable_helper.rb
module LableHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/items/_disc_fields.html.erb
<div class="nested-fields well well-compact">
  <div class="form-group">
  	<h3>DISC</h3>
    <%= link_to_remove_association "削除", f %>
  </div>
<div class="songs">
	<%= f.text_field :disc_name %>
	<h3>SONG</h3>
	<%= link_to_remove_association "削除", f %>
	<%= f.fields_for :songs do |song| %>
	<%= render 'song_fields', f: song %>
	<% end %>
	<div class="links">
		<%= link_to_add_association "曲追加", f, :songs %>
	</div>
</div>

app/views/items/_song_fields.html.erb
<div class="form-group">
	<%= f.text_field :song_title %>
</div>

app/views/items/edit.html.erb
<h1>商品編集</h1>


    <%= form_for(@item) do |f| %>

         <h4>ジャケット写真</h4>

    <%= f.attachment_field :item_image %>

        <ul class='create_item'>
          <li class="item_type">
             <label for="item_type">シングル or アルバム</label>
             <%= f.select :item_type, [["シングル", "シングル"], ["アルバム", "アルバム"]], :prompt => "選択してください" %>
          </li>

          <li class="item_states">
             <label for="item_states">新品 / 中古</label>
             <%= f.select :item_states, [["新品", "新品"], ["中古", "中古"]], :prompt => "選択してください" %>
          </li>

          <li class="item_name">
             <label for="item_name">タイトル</label>
             <%= f.text_field :item_name %>
          </li>

          <li class="artist_name">
            <label for="artist_name">アーティスト名</label>
            <%= f.select :artist_id, @artists.map{|t| [t.artist_name, t.id]} %>
          </li>

          <li class="lable_name">
            <label for="lable_name">レーベル</label>
            <%= f.select :lable_id, @lables.map{|t| [t.lable_name, t.id]} %>
          </li>

          <li class="genre_name">
            <label for="genre_name">ジャンル</label>
            <%= f.select :genre_id, @genres.map{|t| [t.genre_name, t.id]} %>
          </li>

          <li class="price">
             <label for="price">価格</label>
             <%= f.text_field :price %>
          </li>

          <li class="stock">
            <label for="stock">在庫数</label>
              <%= f.text_field :stock %> 枚
          </li>

          <div id="discs">
            <%= f.fields_for :discs do |disc| %>
            <%= render 'disc_fields', f: disc %>
            <% end %>
            <div id="links">
            </div>
          </div>

             <%= f.submit '送信', class: "btn btn-primary" %>
          </ul>

      <% end %>

app/views/items/index.html.erb
  <div id="sampleCarousel" class="carousel slide" data-ride="carousel">


        <ol class="">
          <li class="active" data-target="#sampleCarousel" data-slide-to="0"></li>
          <li data-target="#sampleCarousel" data-slide-to="1"></li>
          <li data-target="#sampleCarousel" data-slide-to="2"></li>
        </ol>


        <div class="carousel-inner" role="listbox" style="height:400px;"  >
          <div class="item active picture">
            <h1>NEWCD</h1>
            <img src="http://static.simpledesktops.com/uploads/desktops/2012/01/16/simpledesktop.png.625x385_q100.png" alt="First slide" style="height:400px;">
          </div>
          <div class="item picture">
            <img src="http://kabegami.org/wp-content/uploads/2013/03/t3lhox.jpg" alt="Second slide" style="height:400px;">
          </div>
          <div class="item picture">
            <img src="http://kabegami.org/wp-content/uploads/2013/09/KWteoN.jpg" alt="Third slide" style="height:400px;">
          </div>
        </div>


        <a class="left carousel-control" href="#sampleCarousel" role="button" data-slide="prev">
          <span class="" aria-hidden="true"></span>
          <span class="sr-only">前へ</span>
        </a>


        <a class="right carousel-control" href="#sampleCarousel" role="button" data-slide="next">
          <span class="" aria-hidden="true"></span>
          <span class="sr-only">次へ</span>
        </a>


    </div>


  <div class="row clearfix">
      <div class="search-artist">
          <%= search_form_for @search, url: items_path do |f| %>
          <%= f.label :商品検索 %>
          <%= f.search_field :item_name_cont %>
          <%= f.submit "検索" %>
          <% end %>
      </div>
      <div class="col-lg-3">
        <% @rank.each.with_index(1) do |rank, i| %>
        <div class="rank">
          <h3 class="ranking"><%= "第#{i}位" %></h3>
          <%= rank.item_name %>
        </div>
        <% end %>
      </div>
      <div class="col-lg-9">
            <% @items.each do |item|%>
            <div class="item-list">
              <div class="item-image">
                 <%= attachment_image_tag item, :item_image, size: "100x100", fallback: "no_image.jpg" %>
              </div>
              <div class="item-name">
                 <p><%= link_to item.item_name, item_path(item.id) %></p>
              </div>
              <div class="artist-name">
                 <p><%= link_to item.artist.artist_name, artist_path(item.artist.id) %></p>
              </div>
              <div class="item-price">
                <p> ¥ <%= item.price %></p>
              </div>
              <div class="item-stock">
                  <% if item.stock == 0 %>
                    <%= 'Sold Out!!' %>
                  <% end %>
              </div>
            </div>

              <% end %>
      </div>
      <div class="paginate">
            <%= paginate @items, class: "paginate" %>
      </div>
  </div>
</div>

app/views/items/index_used.html.erb
  <div id="sampleCarousel" class="carousel slide" data-ride="carousel">


        <ol class="slide-top">
          <li class="active" data-target="#sampleCarousel" data-slide-to="0"></li>
          <li data-target="#sampleCarousel" data-slide-to="1"></li>
          <li data-target="#sampleCarousel" data-slide-to="2"></li>
        </ol>


        <div class="carousel-inner" role="listbox" style="height:400px;"  >
          <div class="item active">
            <img src="https://d2l930y2yx77uc.cloudfront.net/production/uploads/images/5028219/picture_pc_1c5215de6fb72cfebe54a17746e35411.jpg" alt="First slide" style="height:400px; width:100%;" >
          </div>
          <div class="item">
            <img src="https://i1.wp.com/akirayoshida.com/diary/wp/wp-content/uploads/2016/02/a764fa0b0f6a8ab080fcddddec44718b.jpg?fit=700%2C394&ssl=1" alt="Second slide" style="height:400px; width:100%;">
          </div>
          <div class="item">
            <img src="https://i1.wp.com/akirayoshida.com/diary/wp/wp-content/uploads/2016/02/a764fa0b0f6a8ab080fcddddec44718b.jpg?fit=700%2C394&ssl=1" alt="Third slide" style="height:400px; width:100%;">
          </div>
        </div>


        <a class="left carousel-control" href="#sampleCarousel" role="button" data-slide="prev">
          <span class="" aria-hidden="true"></span>
          <span class="sr-only">前へ</span>
        </a>


        <a class="right carousel-control" href="#sampleCarousel" role="button" data-slide="next">
          <span class="" aria-hidden="true"></span>
          <span class="sr-only">次へ</span>
        </a>


  </div>



<div class="used-information">
  <h1 class="usedcd">U S E D C D</h1>
    <div class="row clearfix">
        <div class="search-artist">
            <%= search_form_for @search, url: items_path do |f| %>
            <%= f.label :商品検索 %>
            <%= f.search_field :item_name_cont %>
            <%= f.submit "検索" %>
            <% end %>
        </div>
        <div class="col-lg-3">
          <% @rank.each.with_index(1) do |rank, i| %>
          <div class="rank">
            <h3 class="ranking"><%= "第#{i}位" %></h3>
            <%= rank.item_name %>
          </div>
          <% end %>
        </div>
        <div class="col-lg-9">
              <% @items.each do |item|%>
              <div class="item-list">
                <div class="item-image">
                   <%= attachment_image_tag item, :item_image, size: "100x100", fallback: "no_image.jpg" %>
                </div>
                <div class="item-name">
                   <p><%= link_to item.item_name, item_path(item.id) %></p>
                </div>
                <div class="artist-name">
                   <p><%= link_to item.artist.artist_name, artist_path(item.artist.id) %></p>
                </div>
                <div class="item-price">
                  <p> ¥ <%= item.price %></p>
                </div>
                <div class="item-stock">
                    <% if item.stock == 0 %>
                      <%= 'Sold Out!!' %>
                    <% end %>
                </div>
              </div>

                <% end %>
        </div>
        <div class="paginate">
              <%= paginate @items, class: "paginate" %>
        </div>
    </div>
</div>

app/views/items/new.html.erb
<h1>追加商品</h1>


		<%= form_for(@item) do |f| %>

			   <h4>ジャケット写真</h4>

		<%= f.attachment_field :item_image %>
	<div class="artist">
		<%= link_to "アーティスト追加", new_artist_path %>
	</div>
	<div class="genre">
		<%= link_to "ジャンル追加", genre_index_path %>
	</div>
	<div class="lable">
		<%= link_to "レーベル追加", lable_index_path %>
	</div>

				<ul class='create_item'>
					<li class="item_type">
					   <label for="item_type">シングル or アルバム</label>
					   <%= f.select :item_type, [["シングル", "シングル"], ["アルバム", "アルバム"]], :prompt => "選択してください" %>
					</li>

					<li class="item_states">
					   <label for="item_states">新品 / 中古</label>
					   <%= f.select :item_states, [["新品", "新品"], ["中古", "中古"]], :prompt => "選択してください" %>
					</li>

					<li class="item_name">
					   <label for="item_name">タイトル</label>
					   <%= f.text_field :item_name %>
					</li>

					<li class="artist_name">
						<label for="artist_name">アーティスト名</label>
						<%= f.select :artist_id, @artists.map{|t| [t.artist_name, t.id]}, :prompt => "選択してください" %>
					</li>

					<li class="lable_name">
						<label for="lable_name">レーベル</label>
						<%= f.select :lable_id, @lables.map{|t| [t.lable_name, t.id]}, :prompt => "選択してください" %>
					</li>

					<li class="genre_name">
						<label for="genre_name">ジャンル</label>
						<%= f.select :genre_id, @genres.map{|t| [t.genre_name, t.id]}, :prompt => "選択してください" %>
					</li>

					<li class="price">
					   <label for="price">価格</label>
					   <%= f.text_field :price %>
					</li>

					<li class="stock">
						<label for="stock">在庫数</label>
					    <%= f.text_field :stock %> 枚
					</li>

					<div id="discs">
						<%= f.fields_for :discs do |disc| %>
						<%= render 'disc_fields', f: disc %>
						<% end %>
						<div id="links">
							<%= link_to_add_association 'ディスク追加',f, :discs %>
						</div>
					</div>

					   <%= f.submit '商品登録', class: "btn btn-primary" %>
			    </ul>

			<% end %>

app/views/items/show.html.erb
<div class="container">
     <h1 class="item-detail-main-title"><span class="label label-default">Detail</span></h1>

      <div class="col-lg-5">
        <%= attachment_image_tag @item, :item_image, size: '400x400', fallback: "no_image.jpg" %>
        <div class="user-signed-in-menu">
         <div class="cart-function">
  <% if user_signed_in? %>
          <%= form_for @cart_disc, url: cart_add_item_path(id: @item.id) do |f| %>
             <%= f.label :cart_item, "枚数を選択" %>
             <%= f.select :cart_item, [1,2,3,4,5,6,7,8,9,10] %>
             <%= f.submit 'カートに入れる', class: "btn btn-primary" %>
          <% end %>
         </div>
       <div class="favorite-function">
        <% if @item.favorited_by?(current_user) %>
          <li>
            <%= link_to item_favorite_path(@item, current_user.favorites), method: :delete do %>
              <i class="fa fa-heart" aria-hidden="true" style="color: red;"></i>
              <%= @item.favorites.count %>いいね
            <% end %>
          </li>
      <% else %>
          <li>
            <%= link_to item_favorites_path(@item), method: :post do %>
              <i class="far fa-heart"></i>
              <%= @item.favorites.count %>いいね
            <% end %>
         </li>
       <% end %>
<% else %>
        <i class="fa fa-heart" aria-hidden="true" style="color: red;"></i>
         <%= @item.favorites.count %>いいね
  <% end %>
       </div>
     </div>
　　　　<div class="user-singed-in-menu">
              <div class="admin-limited-menu">
      <% if user_signed_in? %>
        <% if current_user.admin == true %>
                <%= link_to "編集", edit_item_path(@item.id), class: "btn btn-success" %>
                <%= link_to "削除", item_path(@item), method: :delete, "data-confirm" => "消しちゃうの？消さないで！お願い！100円あげるから！", class: "btn btn-danger" %>
        <% end %>
      <% end %>
              </div>

          <div class="reviews-index">
              <div class="dropdown">
                  <button class="btn btn-default dropdown-toggle" type="button" data-toggle="dropdown">
                    コメント一覧
                    <span class="caret"></span>
                  </button>
                      <ul class="dropdown-menu" role="menu" style="max-height:200px;overflow:scroll;" >
                        <li role="presentation">
                            <% @item.reviews.each do |review|  %>
                          <a href="#">
                            <%= review.review_text %>
                    <% if user_signed_in? %>
                       <% if review.user_id == current_user.id %>
                            <%= link_to '削除', item_review_path(@item, current_user.reviews), method: :delete, class: "btn btn-primary btn-xs" %>
                       <% end %>
                    <% end %>
                            <% end %>
                            </a>
                          </li>
                      </ul>
              </div>
          </div>
        </div>
      </div>


    <div class = 'col-lg-7'>
      <div class="item-detail">
        <h1>[CD<%= @item.item_type %>]&nbsp;&nbsp;&nbsp;&nbsp;<span class="label label-success"><%= @item.item_states %></span></h1>

         <h4><span class="label label-default">タイトル</span></h4>
           <h2><%= @item.item_name %></h2>

         <h4><span class="label label-default">アーティスト</span></h4>
           <%= link_to artist_path(@item.artist.id) do %>
             <h2><%= @item.artist.artist_name %></h2>
           <% end %>

         <h4><span class="label label-default">価格</span></h4>
           <h2>¥<%= @item.price %></h2>

         <h4><span class="label label-default">レーベル</span></h4>
           <h2><%= @item.lable.lable_name %></h2>

         <h4><span class="label label-default">ジャンル</span></h4>
           <h2><%= @item.genre.genre_name %></h2>

            <% @item.discs.each do |disc| %>
               <%= disc.disc_name %>
                 <% disc.songs.each do |song| %>
                  <%= song.song_title %>
                 <% end %>
               <% end %>
      </div>

       <div class="review-create-form">
    <% if user_signed_in? %>
           <%= form_for @review, url: item_reviews_path(item_id: @item.id) do |f| %>
             <div class = 'review'>
                  <%= f.hidden_field :review_title, :value => "title" %>
              <div>
                  <h3 class="review-upload-form"><span class="label label-primary">コメント投稿</span></h3>
                  <%= f.text_area :review_text, :size=>"60x2" %>
              </div>
                 <%= f.submit '送信', :class => "btn btn-primary btn-lg active" %>
           <% end %>
            </div>
    <% end %>
       </div>
    </div>
</div>