config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :items do
    resources :reviews, only:[:create, :destroy]
    resources :favorites, only:[:create, :destroy]

    collection do
      get :index_used
    end
  end

  resources :users do
    collection do
      get :favorites
      get :top
      get :purchase_history
    end
    member do
      patch :delivery_update
      post :favorite
      get :delete
      post :delete
    end
  end

  get '/admin/users/:id/edit' => 'users#admin_edit', as: 'admin_edit'

  resources :contacts, only:[:create, :show, :index]
  get '/contacts_top' => 'contacts#top', as: 'contact_top'

  resources :carts, only:[:index, :show]
  get '/function/:id' => 'carts#function', as: 'cart_function'
  get '/complete' => 'carts#complete', as: 'cart_complete'
  post '/carts/:id/add_item'  => 'carts#add_item', as: 'cart_add_item'
  post '/carts/:id' => 'carts#address_change', as: 'carts_address_change'
  post '/buy' => 'carts#buy', as: 'purchase_histories'
  patch '/carts/:id/update' => 'carts#update', as: 'cart_update'
  delete '/carts/:id/destroy' => 'carts#delete', as: 'cart_delete'

  resources :homes, only:[:index]
  get '/' => 'homes#top',as: "top"

  resources :artists, only:[:show, :create, :new, :destroy]
  get 'artists/:id/new_item' => 'artists#new_item', as: 'artist_new_item'
  get 'artists/:id/used_item' => 'artists#used_item', as: 'artist_used_item'

  resources :genre, only:[:index, :create]
  resources :lable, only:[:index, :create]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/artist.rb
class Artist < ApplicationRecord

  has_many :items

  attachment :artist_image

  validates :artist_name, presence: true

end

app/models/cart.rb
class Cart < ApplicationRecord

	belongs_to :user
	belongs_to :item
	has_one :purchase_history

    acts_as_paranoid
end

app/models/contact.rb
class Contact < ApplicationRecord

	belongs_to :user

	validates :contact_title, presence: true
	validates :contact_text, presence: true

end

app/models/delivery.rb
class Delivery < ApplicationRecord

	has_many :purchase_histories

end

app/models/disc.rb
class Disc < ApplicationRecord

  belongs_to :item, required: true
  has_many :songs, dependent: :destroy

  accepts_nested_attributes_for :songs, reject_if: :all_blank, allow_destroy: true

  validates :disc_name, presence: true


end

app/models/favorite.rb
class Favorite < ApplicationRecord

	belongs_to :user
    belongs_to :item

end

app/models/genre.rb
class Genre < ApplicationRecord

  has_many :items

  validates :genre_name, presence: true

end

app/models/item.rb
class Item < ApplicationRecord

  belongs_to :artist, required: true
  belongs_to :lable, required: true
  belongs_to :genre, required: true

  has_many :discs, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :carts

  attachment :item_image

  accepts_nested_attributes_for :discs, reject_if: :all_blank, allow_destroy: true

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  validates :item_name, presence: true
  validates :item_states, presence: true
  validates :item_type, presence: true
  validates :price, presence: true
  validates :stock, presence: true

end

app/models/lable.rb
class Lable < ApplicationRecord

  has_many :items

  validates :lable_name, presence: true

end

app/models/review.rb
class Review < ApplicationRecord

	belongs_to :user
	belongs_to :item

	validates :review_title, length: { in:1..20}
	validates :review_text, length: { in:1..200}

end

app/models/song.rb
class Song < ApplicationRecord

	belongs_to :disc, required: true

	validates :song_title, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :contacts
  has_many :favorites, dependent: :destroy
  has_many :purchase_histories
  has_many :reviews, dependent: :destroy
  has_many :carts, dependent: :destroy

  validates :email, presence: true
  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :zip_code, presence: true
  validates :address, presence: true
  validates :phone_number, presence: true

  paginates_per 12

  acts_as_paranoid
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/genre_helper.rb
module GenreHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/lable_helper.rb
module LableHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NEWSED</title>
    <link rel="stylesheet" href="css/skippr.css"> <!-- skipprのcssファイルを読み込む！ -->
    <link href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" rel="stylesheet">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>

            <p class = "title-newsed"><%= link_to "NEWSED", top_path, :style=>"color:white;" %></p>

        <% if flash[:notice]%>
           <div class="alert alert-warning alert-dismissible fade in" role="alert">
                <button type="button" class="close" data-dismiss="alert">
                  <span aria-hidden="true">×</span>
                </button>
                <strong>Info:</strong><%= flash[:notice]%>
                <p><a href="#" data-dismiss="alert">閉じる</a></p>
          </div>
        <% end %>

             <% if user_signed_in? %>
               <span class="user_first_name"><i class="fas fa-user-alt"></i>&nbsp;&nbsp;
                <%= current_user.last_name %><%= current_user.first_name %> さん</span>
             <% end %>
         <nav>
              <ul class="nav-list">
            <% if user_signed_in? %>
                <li class="nav-list-item"><i class="fas fa-shopping-cart" style="color: white;" ></i> 
                  <%= link_to "カート一覧", carts_path(current_user.carts), :style=>"color:white;" %></li>
                <li class="nav-list-item"><i class="fas fa-compact-disc" style="color: white;" ></i> 
                  <%= link_to " 新品一覧", items_path, :style=>"color:white;" %></li>
                <li class="nav-list-item"><i class="fab fa-old-republic" style="color: white;" ></i> 
                  <%= link_to " 中古一覧", index_used_items_path, :style=>"color:white;" %></li>
                <li class="nav-list-item"><i class="fas fa-home" style="color: white;" ></i> 
                  <%= link_to " マイページ", top_users_path, :style=>"color:white;" %></li>
                <li class="nav-list-item"><i class="fas fa-sign-in-alt" style="color: white;" ></i> 
                  <%= link_to " ログアウト", destroy_user_session_path, method: :delete, :style=>"color:white;" %></li>

            <% else %>

                <li class="nav-list-item"><i class="fas fa-compact-disc" style="color: white;" ></i> 
                  <%= link_to " 新品一覧", items_path, :style=>"color:white;" %></li>
                <li class="nav-list-item"><i class="fab fa-old-republic" style="color: white;" ></i> 
                  <%= link_to " 中古一覧", index_used_items_path, :style=>"color:white;" %></li>
                <li class="nav-list-item"><i class="fas fa-axe-battle" style="color: white;" ></i> 
                  <%= link_to " 会員登録", new_user_registration_path, :style=>"color:white;" %></li>
                <li class="nav-list-item"><i class="fas fa-sign-in-alt" style="color: white;" ></i> 
                  <%= link_to " ログイン", new_user_session_path, :style=>"color:white;" %></li>
            <% end %>
               </ul>
         </nav>
    </header>

    <%= yield %>

    <footer>
      <p class="contact-text"><%= link_to "お問い合わせ", contact_top_path, :style=>"color:white;", class: "btn btn-warning" %></p>
      <p class="foter-text">CopyRight 2019 NEWSED All right reserved.</p>
    </footer>
  </body>
</html>